### ISSUE TITLE
Add historical shelter data

### ISSUE THREAD

**Issue by patcon** [CivicTechTO/toronto-shelter-map#1]
Reticketed from old repo

---------

Ok, so @wolfewylie's has been that he's been scraping the data links below for 2 years. (Yaaaaaaay! Thanks)

- [Google Spreadsheet: Daily Toronto Shelter Capacity](https://docs.google.com/spreadsheets/d/1YMbqVP8uc_3RIAtKd1cmt481htgb9Y6ofehBQHxPf6c/edit#gid=0)

Is this data that would be helpful to get into the visualization? (We shouldn't treat that as a forgone conclusion, but perhaps find out whether front-line folks or journalists would indeed find it helpful.)

If it would be helpful, how? Anyone have thoughts on how this could fit? (We could treat this github issue as a high-level one for now.)

**Comment by andrewcarreiro** [comment]
Closing due to new focus
