### ISSUE TITLE
Fix map

### ISSUE THREAD

**Issue by patcon** [CivicTechTO/toronto-shelter-map#10]
Hi all! I know that you've pivoted to something else, but might still be beneficial to keep past artefacts working, so that people understand your previous efforts and productivity!

(I was trying to link to it during an introduction to Pam Ryan, Director of Innovation at the Toronto Public Library, and couldn't.)

Lemme know if you need any help!

**Comment by andrewcarreiro** [comment]
Oof, I went back in time to before I borked it and it looks like the original data feed we hit is no longer available. It might be a bit harder for us to get this repo back up and running.

**Comment by patcon** [comment]
Thanks @andrewcarreiro! Can you point to where you found the url it was pulling from? I can sleuth, but not sure where to find the dead link

**Comment by patcon** [comment]
Ok, maybe figured it out :) seems that it was this move from relative to absolute links in HEAD and elsewhere, which breaks github pages:
https://github.com/CivicTechTO/toronto-shelter-map/commit/51357f04a988a552f27d21736f5c6b843ad043e5

Also, the temporary arcgis dataportal probably moved to a more perma-home. My compy is super slow right now, but if no one else has time, I'll try to dig in later when I'm doing less tabs :)

**Comment by andrewcarreiro** [comment]
Closing due to new focus
