### ISSUE TITLE
Compile stakeholder list for user research

### ISSUE THREAD

**Issue by patcon** [CivicTechTO/toronto-shelter-map#9]
Meeting context: [2018-01-23 Hacknight](https://hackmd.io/s/SJZsjLSHG#)

We don't need to contact anyone yet, but we would do well to brainstorm a stakeholder list of who we are intending this to create value for. We should aspire to talk to them sooner rather than later.

We should prob have a solid plan before reaching out to anyone with actual questions or requests for time.

Example spreadsheet format: https://docs.google.com/spreadsheets/d/1bzz7W9EcLUTCWl2o5CepCbNrRUkSvpzVPfYlQ2nV5dM/edit#gid=0

## To Do
- [x] start a spreadsheet
- [x] link to it in our docs (wiki?)
- [ ] migrate ideas from notes
- [ ] do outreach to discover more stakeholders for list (rolling intake forms -- ie. telling people they can add groups they can think of, and forward to other who might know more)

**Comment by andrewcarreiro** [comment]
I feel that I'll need some initial guidance on the current system before I could define who the stakeholders will be. At the next CivicTechTO meetup, we should pitch the project asking if anyone has knowledge in this space that we could talk to.

**Comment by patcon** [comment]
I will admit that I feel it a bit backwards from that :) I was hoping to talk to stakeholders (using some hypotheses about the value we anticipate we could offer) before imagining the system any further?

**Comment by patcon** [comment]
But I LOVE the idea of pitching looking for people -- just no reliable way to know they'll be in the room if we don't reach out first. A common tactic is to invite people to the hacknight, because it's hard to assume the right frontline folks will be there with regularity (though we might luck out!)

**Comment by andrewcarreiro** [comment]
@patcon I think that I don't have the foundational knowledge about the existing shelter system to be able to effectively brainstorm. Maybe someone at the next hack night would be able to help. My goal would be to create some kind of primer on the shelter system for both for myself and for any new people who would like to join.

**Comment by andrewcarreiro** [comment]
Closing due to new focus
